---
# handlers file for roundcube

- name: restart apache2
  ansible.builtin.systemd:
    name: apache2.service
    state: restarted

- name: restart php8.2-fpm
  ansible.builtin.systemd:
    name: php8.2-fpm.service
    state: restarted
